#logging.file.name=logs/app.log
#logging.pattern.file=%d %p %c{1.} {%t} %m%n

---
spring:
  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:file:C:/Users/ZukoM/Documents/GitHub/neiu-cs-321/valet-parking/dbdata
    username: admin
    password:
    driver: org.h2.Driver

server:
  port: 8080
  error:
    whitelabel:
      enabled: false
    path: /error

valet:
  vehicles:
    pageSize: 5
