-- delete from Vehicle;
-- delete from Vehicle_Category;
-- -- delete from User;
--
-- insert into Vehicle_Category(id, type)
-- values('SDN', 'SEDAN');
-- insert into Vehicle_Category(id, type)
-- values('CPE', 'COUPE');
-- insert into Vehicle_Category(id, type)
-- values('TRK', 'TRUCK');
-- insert into Vehicle_Category(id, type)
-- values('HTK', 'HATCHBACK');
-- insert into Vehicle_Category(id, type)
-- values('SPT', 'SPORT');
-- insert into Vehicle_Category(id, type)
-- values('CVT', 'CONVERTIBLE');